config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admin do
  	resources :users,       only:[:index, :show, :edit, :update, :destroy]
  	resources :films,		only:[:new, :create, :index, :show, :edit, :update, :destroy]
  	resources :tags,		only:[:create, :index, :show, :update]
  	resources :reviews,		only:[:edit, :update, :destroy]
  	get "search_films" => "films#search",as: 'search_films'
  	get "search_users" => "users#search",as: 'search_users'
  end


  resources :users, 		only:[:show, :edit, :update, :resign, :destroy, :follows, :followers] do
  	resources :relationships,	only:[:create, :destroy]
	get :follows, on: :member
    get :followers, on: :member
    # on: :memberはresources以外のアクションへのルーティングも定義
  end

  resources :films,			only:[:index, :show, :edit, :update, :destroy] do
  	resources :wishes,			only:[:create, :destroy]
  	resources :dones,			only:[:create, :destroy]
  	resources :mybests,			only:[:create, :destroy]
  	resources :reviews,			only:[:new, :create, :show, :edit, :update, :destroy] do
  		resources :good_reviews,	only:[:create, :destroy]
  	end
  end
  get "search_films" => "films#search",as: 'search_films'
  get "search_users" => "users#search",as: 'search_users'

  resources :tags,			only:[:create, :index, :show, :update]
  resources :contacts,		only:[:new, :create, :destroy]


  root "films#index"
end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }

	has_many :wishes, 		dependent: :destroy
	has_many :dones, 		  	dependent: :destroy
	has_many :mybests, 		dependent: :destroy
	has_many :reviews, 		dependent: :destroy
	has_many :good_reviews, 	dependent: :destroy

	validates :name,          presence: true,
								uniqueness: true,
								length: { minimum: 1, maximum: 20 },
								format: { with: /\A[a-z0-9]+\z/i }
	validates :email, 		presence: true,
								uniqueness: true,
								format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

##refile
	attachment :image

##フォロー機能
	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower

	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following


	def followed_by?(user)
	passive_relationships.find_by(following_id: user.id).present?
	end

##devise

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable

	def email_required?
	false
	end
	def email_changed?
	false
	end

##検索

	def self.search(search)
		if search.present?
			User.where(['name LIKE? OR email LIKE?', "%#{search}%","%#{search}%"])
		else
			User.all
		end
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :show, :edit, :update, :destroy]

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:success] = "プロフィールを編集しました！"
      redirect_to admin_user_path(user)
    else
      flash[:warning] = "プロフィールの編集に失敗しました！"
      redirect_to edit_admin_user_path(user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def search
    @users = User.search(params[:search])
    render :search
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :image)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show, :edit, :update, :resign, :destroy, :follows, :followers]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @wishes = Wish.where(user_id: @user.id)
    @dones = Done.where(user_id: @user.id)
    @mybests = Mybest.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:success] = "プロフィールを編集しました！"
      redirect_to user_path(user)
    else
      flash[:warning] = "プロフィールの編集に失敗しました！"
      redirect_to edit_user_path(user)
    end
  end

  def resign
  end

  def destroy
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :image)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(@user) unless @user == current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">

	<div class="col">
	</div>

	<div class="col-8">
		<div class="card">
			<div class="card-header">
				<h4>プロフィール編集</h4>
			</div>
			<div class="card-body">
				<div class="form-group">
					<%= form_for(@user) do |f| %>
						<% if @user.errors.any? %>
						  <div id="error_explanation" class="alert alert-danger">
						    <ul>
						      <% @user.errors.full_messages.each do |message| %>
						        <li><%= message %></li>
						      <% end %>
						    </ul>
						  </div>
						<% end %>

						<div class="form-group">
						    <label for="exampleFormControlInput1">プロフィール画像</label>
							<%= f.attachment_field :image, class:"form-control-file" %>
						</div>
						<div class="form-group">
						    <label for="exampleFormControlInput1">ユーザー名</label>
							<%= f.text_field :name, class:"form-control", placeholder:"ユーザー名"%>
						</div>
						<div class="form-group">
						    <label for="exampleFormControlInput1">メールアドレス</label>
							<%= f.text_field :email, class:"form-control", placeholder:"メールアドレス"%>
						</div>
						<div class="card-text text-center">
							<%= link_to "戻る", user_path(@user), class: "btn btn-light border border-seconday"%>
							<%= f.submit "確定", class: 'btn btn-primary text-center' %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>

	<div class="col">
	</div>

</div>

app/views/users/followers.html.erb
<div class="row">
	<div class="col">
	</div>

	<div class="col-8">
		<div class="card">
			<div class="card-header">
				<h3><%= @user.name %>さんのフォロワー</h3>
			</div>
			<div class="card-body">
				<table class="table">
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '40x40' %>
							</td>
							<td><%= link_to user.name, user_path(user.id) %></td>
							<td><span class="badge badge-warning">観たい!<br>
								<%= user.wishes.count %></span></td>
							<td><span class="badge badge-warning">観た!<br>
								<%= user.dones.count %></span></td>
							<td><span class="badge badge-warning">Mybest!<br>
								<%= user.mybests.count %></span></td>
							<td>
							<% if current_user != user %>
							    <% if user.followed_by?(current_user) %>
							        <%=link_to user_relationship_path(user.id), method: :delete do %>
							        	<button class="btn btn-primary">フォロー中</button>
							        <% end %>
							    <% else %>
							        <%=link_to user_relationships_path(user.id), method: :post do %>
										<button class="btn btn-outline-primary">フォローする</button>
							        <% end %>
							    <% end %>
							<% end %>
							</td>
						</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>

	<div class="col">
	</div>

</div>

app/views/users/follows.html.erb
<div class="row">
	<div class="col">
	</div>

	<div class="col-8">
		<div class="card">
			<div class="card-header">
				<h3><%= @user.name %>さんのフォロー</h3>
			</div>
			<div class="card-body">
				<table class="table">
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '40x40' %>
							</td>
							<td><%= link_to user.name, user_path(user.id) %></td>
							<td><span class="badge badge-warning">観たい!<br>
								<%= user.wishes.count %></span></td>
							<td><span class="badge badge-warning">観た!<br>
								<%= user.dones.count %></span></td>
							<td><span class="badge badge-warning">Mybest!<br>
								<%= user.mybests.count %></span></td>
							<td>
							<% if current_user != user %>
							    <% if user.followed_by?(current_user) %>
							        <%=link_to user_relationship_path(user.id), method: :delete do %>
							        	<button class="btn btn-primary">フォロー中</button>
							        <% end %>
							    <% else %>
							        <%=link_to user_relationships_path(user.id), method: :post do %>
										<button class="btn btn-outline-primary">フォローする</button>
							        <% end %>
							    <% end %>
							<% end %>
							</td>
						</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>

	<div class="col">
	</div>

</div>

app/views/users/show.html.erb
<br>

<div class="row">
	<div class="col-1">
	</div>
	<div class="col-2">
		<% if current_user == @user %>
			<h2>マイページ</h2>
		<% end %>
		<div class="text-center">
			<%= attachment_image_tag @user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '150x150' %>
		</div>
		<div class="card-body text-center">
			<p class="text-center"><%= @user.name %>さん</p>
			<div class="btn-group">
				<%=link_to follows_user_path(@user.id) do %>
					<button type="button" class="btn btn-light btn-sm border text-center">
						フォロー<br>
						<span class="badge badge-primary"><%= @user.active_relationships.count %></span>
					</button>
				<% end %>
				<%=link_to followers_user_path(@user.id) do %>
					<button type="button" class="btn btn-light btn-sm border">
						フォロワー<br>
						<span class="badge badge-primary"><%= @user.passive_relationships.count %></span>
					</button>
				<% end %>
			</div>
			<br>
			<div>
				<% if current_user != @user %>
				    <% if @user.followed_by?(current_user) %>
				        <%=link_to user_relationship_path(@user.id), method: :delete do %>
				        	<button class="btn btn-primary btn-block">フォロー中</button>
				        <% end %>
				    <% else %>
				        <%=link_to user_relationships_path(@user.id), method: :post do %>
							<button class="btn btn-outline-primary btn-block">フォローする</button>
				        <% end %>
				    <% end %>
				<% end %>
			</div>
		</div>
		<br>
		<% if current_user == @user %>
	    	<%=link_to"プロフィール編集", edit_user_path(@user), class:"btn btn-secondary btn-block" %>
	    <% end %>
	</div>

	<div class="col-9">
		<nav>
		  <div class="nav nav-tabs" id="nav-tab" role="tablist">
		    <a class="nav-item nav-link active text-reset border border-white" id="nav-wish-tab" data-toggle="tab" href="#nav-wish" role="tab" aria-controls="nav-wish" aria-selected="true">観たい!</a>
		    <a class="nav-item nav-link text-reset border border-white" id="nav-done-tab" data-toggle="tab" href="#nav-done" role="tab" aria-controls="nav-done" aria-selected="false">観た!</a>
		    <a class="nav-item nav-link text-reset border border-white" id="nav-mybest-tab" data-toggle="tab" href="#nav-mybest" role="tab" aria-controls="nav-mybest" aria-selected="false">Mybest!</a>
		    <a class="nav-item nav-link text-reset border border-white" id="nav-review-tab" data-toggle="tab" href="#nav-review" role="tab" aria-controls="nav-review" aria-selected="false">レビュー</a>
		  </div>
		</nav>
		<div class="tab-content" id="nav-tabContent">
		  <div class="tab-pane fade show active" id="nav-wish" role="tabpanel" aria-labelledby="nav-wish-tab">
		  	<div class="card-columns">
				<% @wishes.each do |wish| %>
					<a href="<%= film_path(wish.film_id) %>" class="card text-reset card-hover" style="max-width: 18rem;">
						<div class="card-body">
						  	<p class="card-text text-center"><%= attachment_image_tag wish.film, :image, fallback:"/images/no_images.png", size:'100x150' %></p>
						    <div ><%= wish.film.title %></div>
						    <p class="card-text"><%= wish.film.release %>年</p>
						</div>
					</a>
				<% end %>
			</div>
		  </div>
		  <div class="tab-pane fade" id="nav-done" role="tabpanel" aria-labelledby="nav-done-tab">
		  	<div class="card-columns">
				<% @dones.each do |done| %>
					<a href="<%= film_path(done.film_id) %>" class="card text-reset card-hover" style="max-width: 18rem;">
						<div class="card-body">
						  	<p class="card-text text-center"><%= attachment_image_tag done.film, :image, fallback:"/images/no_images.png", size:'100x150' %></p>
						    <div ><%= done.film.title %></div>
						    <p class="card-text"><%= done.film.release %>年</p>
						</div>
					</a>
				<% end %>
			</div>
		  </div>
		  <div class="tab-pane fade" id="nav-mybest" role="tabpanel" aria-labelledby="nav-mybest-tab">
		  	<div class="card-columns">
				<% @mybests.each do |mybest| %>
					<a href="<%= film_path(mybest.film_id) %>" class="card text-reset card-hover" style="max-width: 18rem;">
						<div class="card-body">
						  	<p class="card-text text-center"><%= attachment_image_tag mybest.film, :image, fallback:"/images/no_images.png", size:'100x150' %></p>
						    <div ><%= mybest.film.title %></div>
						    <p class="card-text"><%= mybest.film.release %>年</p>
						</div>
					</a>
				<% end %>
			</div>
		  </div>
		  <div class="tab-pane fade" id="nav-review" role="tabpanel" aria-labelledby="nav-review-tab">
		  	<% @user.reviews.each do |review| %>
			  	<div class="mypage_review_box">
				  <div class="row no-gutters">
				    <div class="col-2">
				      <div class="card-body text-center">
				      	<%= attachment_image_tag review.film, :image, class: "item-index-jacket-image", fallback: "/images/no_images.png", size: '100x150' %>
				      </div>
				    </div>
				    <div class="col-10">
				      <div class="card-body">
				      	<p class="card-text"><%= review.film.title %></p>
				        <h5 class="card-title"><%= review.title %></h5>
				        <p class="card-text"><%= review.star.to_f %><i id="star-rate-<%= review.id %>"></i></p>
				        <p class="card-body"><%= review.body.truncate(175) %><%= link_to "全部読む", film_review_path(review.film,review)%></p>
				        <p class="card-text"><small class="text-muted"><%= review.created_at.strftime("%Y/%m/%d/%H:%M") %></small></p>
				      </div>
				      <script>
					  $('#star-rate-<%= review.id %>').raty({
					    size: 36,
					    starOff:  '<%= asset_path('/images/star-off.png') %>',
					    starOn : '<%= asset_path('/images/star-on.png') %>',
					    starHalf: '<%= asset_path('/images/star-half.png') %>',
					    half: true,
					    readOnly: true,
					    score: <%= review.star %>,
					  });
					</script>
				   </div>
				  </div>
				</div>
			<% end %>
		  </div>
		</div>
	</div>
</div>

<script>
	$(function(){
	    $('.card').mouseover(function(){
	        $(this).addClass('card_fadecolor');
	    });
	    $('.card').mouseout(function(){
	        $(this).removeClass('card_fadecolor');
	    });
	});
</script>