config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admin do
  	resources :users,       only:[:index, :show, :edit, :update, :destroy]
  	resources :films,		only:[:new, :create, :index, :show, :edit, :update, :destroy]
  	resources :tags,		only:[:create, :index, :show, :update]
  	resources :reviews,		only:[:edit, :update, :destroy]
  	get "search_films" => "films#search",as: 'search_films'
  	get "search_users" => "users#search",as: 'search_users'
  end


  resources :users, 		only:[:show, :edit, :update, :resign, :destroy, :follows, :followers] do
  	resources :relationships,	only:[:create, :destroy]
	get :follows, on: :member
    get :followers, on: :member
    # on: :memberはresources以外のアクションへのルーティングも定義
  end

  resources :films,			only:[:index, :show, :edit, :update, :destroy] do
  	resources :wishes,			only:[:create, :destroy]
  	resources :dones,			only:[:create, :destroy]
  	resources :mybests,			only:[:create, :destroy]
  	resources :reviews,			only:[:new, :create, :show, :edit, :update, :destroy] do
  		resources :good_reviews,	only:[:create, :destroy]
  	end
  end
  get "search_films" => "films#search",as: 'search_films'
  get "search_users" => "users#search",as: 'search_users'

  resources :tags,			only:[:create, :index, :show, :update]
  resources :contacts,		only:[:new, :create, :destroy]


  root "films#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/done.rb
class Done < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/models/film.rb
class Film < ApplicationRecord

	acts_as_taggable_on :performers, :staffs, :genres
	acts_as_taggable

	attachment :image

	has_many :reviews, 	dependent: :destroy
	has_many :wishes, 	dependent: :destroy
	has_many :dones, 	dependent: :destroy
	has_many :mybests, 	dependent: :destroy

	validates :title,   	presence: true
	validates :story,		presence: true
	validates :release,		presence: true
	validates :language,	presence: true
	validates :time,		presence: true

	def self.search(search)
		if search.present?
			Film.where(['title LIKE? OR release LIKE? OR language LIKE?', "%#{search}%","%#{search}%","%#{search}%"])
		else
			Film.all
		end
	end

	def reviewed_by?(user)
	    reviewes.where(user_id: user.id).exists?
	end

	def wished_by?(user)
	    wishes.where(user_id: user.id).exists?
	end

	def doned_by?(user)
	    dones.where(user_id: user.id).exists?
	end

	def mybested_by?(user)
	    mybests.where(user_id: user.id).exists?
	end


end

app/models/film_tag.rb
class FilmTag < ApplicationRecord
end

app/models/good_review.rb
class GoodReview < ApplicationRecord

	belongs_to :user
	belongs_to :review

end

app/models/mybest.rb
class Mybest < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"

end

app/models/review.rb
class Review < ApplicationRecord

	has_many :good_reviews,	dependent: :destroy

	belongs_to :user
	belongs_to :film

	validates :user_id, :uniqueness => {:scope => :film_id}

	default_scope -> { order(created_at: :desc)}

	def good_reviewed_by?(user)
    	good_reviews.where(user_id: user.id).exists?
    end

    def self.top_review
    	Review.find(GoodReview.group(:review_id).order('count(review_id) desc').limit(1).pluck(:review_id))
    end

end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }

	has_many :wishes, 		dependent: :destroy
	has_many :dones, 		  	dependent: :destroy
	has_many :mybests, 		dependent: :destroy
	has_many :reviews, 		dependent: :destroy
	has_many :good_reviews, 	dependent: :destroy

	validates :name,          presence: true,
								uniqueness: true,
								length: { minimum: 1, maximum: 20 },
								format: { with: /\A[a-z0-9]+\z/i }
	validates :email, 		presence: true,
								uniqueness: true,
								format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

##refile
	attachment :image

##フォロー機能
	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower

	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following


	def followed_by?(user)
	passive_relationships.find_by(following_id: user.id).present?
	end

##devise

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable

	def email_required?
	false
	end
	def email_changed?
	false
	end

##検索

	def self.search(search)
		if search.present?
			User.where(['name LIKE? OR email LIKE?', "%#{search}%","%#{search}%"])
		else
			User.all
		end
	end

end

app/models/wish.rb
class Wish < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/controllers/admin/films_controller.rb
class Admin::FilmsController < ApplicationController

  before_action :authenticate_admin!, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      flash[:success] = "映画を作成しました"
      redirect_to new_admin_film_path
    else
      flash[:warning] = "映画を作成できませんでした"
      redirect_to new_admin_film_path
    end
  end

  def index
    @films = Film.all.order("created_at DESC")
    if params[:tag_name]
      @films = @films.tagged_with("#{params[:tag_name]}")
    end
  end

  def search
    @films = Film.search(params[:search])
    render :search
  end

  def show
    @film = Film.find(params[:id])
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    if @film.update(film_params)
       flash[:success] = '"' + @film.title + '"を編集しました'
       redirect_to admin_films_path
    else
       flash[:warning] = "編集に失敗しました"
       redirect_to admin_films_path
    end
  end

  def destroy
    @film = Film.find(params[:id])
    if @film.destroy
       flash[:success] = '"' + @film.title + '"を削除しました'
       redirect_to admin_films_path
    else
       flash[:warning] = "削除に失敗しました"
       redirect_to admin_films_path
    end
  end

  private
    def film_params
        params.require(:film).permit(:title, :image, :story, :based, :release, :time, :language, :performer_list, :staff_list, :genre_list)
    end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
    @films = Film.all.page(params[:page]).per(20)
    if user_signed_in?
      reviews_all = Review.all
      @users = current_user.followings
      @reviews = reviews_all.where(user_id: @users).limit(5).order("created_at DESC")
    else
      @reviews = Review.all.limit(5).order("created_at ASC")
    end
    # タグ検索
    if params[:tag_name]
      @films = @films.tagged_with("#{params[:tag_name]}")
    end
  end

  def search
    @films = Film.search(params[:search])
    render :search
  end

  def show
    @film = Film.find(params[:id])
    @reviews = Review.where(film_id: @film.id).order("created_at DESC").page(params[:page]).per(5)
    @top_reviews = Review.top_review
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :index, :show, :update]

  def create
  end

  def index
  end

  def show
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dones_helper.rb
module DonesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/mybests_helper.rb
module MybestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/films/index.html.erb
<div class="slick">
	<% @films.first(10).each do |film| %>
		<div><%= link_to film_path(film) do %>
				<%= attachment_image_tag film, :image, fallback: "/images/no_images.png", size: '225x300' %>
			 <% end %>
		</div>
	<% end %>
</div>

<div class="row">
	<div class="col">
	</div>
	<div class="col-8">
		<div class="card-columns">
			<% @films.each do |film| %>
				<!-- 平均スコアの算出 -->
				<% starsum = 0 %>
				<% film.reviews.each do |review| %>
					<% review.star.to_i %>
					<% starsum += review.star.to_f %>
				<% end %>
				<% star_av = 0 %>
				<% star_av = starsum.to_f / film.reviews.count %>
				<!-- スコアが無い場合の処理 -->
				<% if star_av.to_f.nan? %>
					<% star_av = 0 %>
				<% end %>
				<div class="card" style="max-width: 18rem;">
					<a href="<%= film_path(film) %>" class="card-body text-reset">
					  	<p class="text-center"><%= attachment_image_tag film, :image, fallback: "/images/no_images.png", size: '150x200' %>
					  	</p>
					    <div class="text-center"><%= star_av.round(2).to_f %><i id="star-rate-<%= film.id %>"></i></div>
						<script>
						  $('#star-rate-<%= film.id %>').raty({
						    size: 36,
						    starOff:  '<%= asset_path('/images/star-off.png') %>',
						    starOn : '<%= asset_path('/images/star-on.png') %>',
						    starHalf: '<%= asset_path('/images/star-half.png') %>',
						    half: true,
						    readOnly: true,
						    score: <%= star_av %>,
						  });
						</script>
					    <p class="film_index-card-content"><%= film.title %></p>
					    <div class="film_index-card-content"><%= film.release %>年</div>
					</a>
					<div class="film_index-card-content">
					    <p>
					    	<% film.performer_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					    <p>
					    	<% film.staff_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					    <p>
					    	<% film.genre_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					</div>
				</div>
			<% end %>
		</div>
		<%= paginate @films %>
	</div>
	<div class="col-2">
 		<div class="films-timeline-box">
			<div class="card-header">
				タイムライン
			</div>
			<% @reviews.each do |review| %>
				<div class="card-body">
					<p><%= attachment_image_tag review.film, :image, fallback: "/images/no_images.png", size: '60x90' %></p>
					<div>
						<%= link_to review.film.title, film_path(review.film), class:"films_timeline_filmtitle" %>
					</div>
					<div class="text-center"><%= review.star.to_f %><i id="review-rate-<%= review.id %>"></i></div>
					<p class="films_timeline_username">
						<%= attachment_image_tag review.user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '20x20' %>
						<%= link_to review.user.name, user_path(review.user_id) %>
					</p>
					<p class="films_timeline_title"><%= review.title %></p>
					<p class="films_timeline_body">
						<%= review.body.truncate(55) %>
						<%= link_to "全部読む", film_review_path(review.film,review)%>
					</p>
					<p class="films_timeline_body"><%= review.created_at.strftime("%Y/%m/%d/%H:%M") %></p>
					<script>
					  $('#review-rate-<%= review.id %>').raty({
					    size: 36,
					    starOff:  '<%= asset_path('/images/star-off.png') %>',
					    starOn : '<%= asset_path('/images/star-on.png') %>',
					    starHalf: '<%= asset_path('/images/star-half.png') %>',
					    half: true,
					    readOnly: true,
					    score: <%= review.star %>,
					  });
					</script>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col">
	</div>
</div>


<!-- film_indexのみに適用するためここに記載 -->
<script>
	$(function(){
	    $('.card').mouseover(function(){
	        $(this).addClass('card_fadecolor');
	    });
	    $('.card').mouseout(function(){
	        $(this).removeClass('card_fadecolor');
	    });
	});
</script>

app/views/films/search.html.erb
<div class="slick">
	<% @films.first(10).each do |film| %>
		<div><%= link_to film_path(film) do %>
				<%= attachment_image_tag film, :image, fallback: "/images/no_images.png", size: '225x300' %>
			 <% end %>
		</div>
	<% end %>
</div>

<div class="row">
	<div class="col">
	</div>
	<div class="col-8">
		<h5 class="text-center">"<%= params[:search] %>"に関する映画<%= @films.count %>作品</h5>
		<div class="card-columns">
			<% @films.each do |film| %>
				<!-- 平均スコアの算出 -->
				<% starsum = 0 %>
				<% film.reviews.each do |review| %>
					<% review.star.to_i %>
					<% starsum += review.star.to_f %>
				<% end %>
				<% star_av = 0 %>
				<% star_av = starsum.to_f / film.reviews.count %>
				<!-- スコアが無い場合の処理 -->
				<% if star_av.to_f.nan? %>
					<% star_av = 0 %>
				<% end %>
				<div class="card" style="max-width: 18rem;">
					<a href="<%= film_path(film) %>" class="card-body text-reset">
					  	<p class="text-center"><%= attachment_image_tag film, :image, fallback: "/images/no_images.png", size: '150x200' %>
					  	</p>
					    <div class="text-center"><%= star_av.round(2).to_f %><i id="star-rate-<%= film.id %>"></i></div>
						<script>
						  $('#star-rate-<%= film.id %>').raty({
						    size: 36,
						    starOff:  '<%= asset_path('/images/star-off.png') %>',
						    starOn : '<%= asset_path('/images/star-on.png') %>',
						    starHalf: '<%= asset_path('/images/star-half.png') %>',
						    half: true,
						    readOnly: true,
						    score: <%= star_av %>,
						  });
						</script>
					    <p class="film_index-card-content"><%= film.title %></p>
					    <div class="film_index-card-content"><%= film.release %>年</div>
					</a>
					<div class="film_index-card-content">
					    <p>
					    	<% film.performer_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					    <p>
					    	<% film.staff_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					    <p>
					    	<% film.genre_list.each do |tag| %>
								<span class="badge badge-info">
									<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
								</span>
							<% end %>
					    </p>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-2">
	</div>
	<div class="col">
	</div>
</div>


<!-- film_indexのみに適用するためここに記載 -->
<script>
	$(function(){
	    $('.card').mouseover(function(){
	        $(this).addClass('card_fadecolor');
	    });
	    $('.card').mouseout(function(){
	        $(this).removeClass('card_fadecolor');
	    });
	});
</script>

app/views/films/show.html.erb
<br>
<div class="row">
	<div class="col">
	</div>
	<div class="col-3">
		<div class="card-body text-center"><%= attachment_image_tag @film, :image, fallback: "/images/no_images.png", size: '300x450' %>
		</div>
<!-- 観たい/観た/マイベスト -->
		<div class="card-body text-center">
			<div class="btn-group">
				<% if user_signed_in? %>
					<div id="wish_button">
						<%= render 'wishes/wish', film: @film %>
          			</div>
					<div id="done_button">
						<%= render 'dones/done', film: @film %>
          			</div>
					<div id="mybest_button">
						<%= render 'mybests/mybest', film: @film %>
          			</div>
				<% else %>
					<%= link_to film_wishes_path(@film), method: :post do %>
					    <button type="button" class="btn btn-xl btn-outline-warning">
					    	観たい!<br>
					      	<span class="badge badge-dark"><%= @film.wishes.count %></span>
					    </button>
					<% end %>
					<%= link_to film_dones_path(@film), method: :post do %>
					    <button type="button" class="btn btn-xl btn-outline-warning">
					      	観た! <br>
					      	<span class="badge badge-dark"><%= @film.dones.count %></span>
					    </button>
					<% end %>
					<%= link_to film_mybests_path(@film), method: :post do %>
						<button type="button" class="btn btn-xl btn-outline-warning">
							MyBest!<br>
							<span class="badge badge-dark"><%= @film.mybests.count %></span>
						</button>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="card-body text-center">
			<%= link_to "レビューを投稿する",new_film_review_path(@film), class:"btn btn-secondary btn-block btn-lg" %>
		</div>
	</div>
<!-- 映画情報 -->
	<div class="col-7">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title"><%= @film.title %></h4>
				<p class="card-text">公開年：<%= @film.release %> ／ 言語：<%= @film.language %> ／ 上映時間：<%= @film.time %>分</p>
				<div class="card">
					<p class="card-header">あらすじ</p>
					<div class="card-body">
						<%= @film.story.truncate(180)%>
						<span class="btn btn-link" data-toggle="modal" data-target="#deleteModal">
	  						全部読む
						</span>
						<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <%= simple_format(@film.story) %>
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-secondary" data-dismiss="modal">
						        	閉じる
						        </button>
						      </div>
						    </div>
						  </div>
						</div>
					</div>
				</div>
			</div>
		</div>
<!-- 映画タグ -->
		<div class="card">
			<div class="card-body">
				<ul class="list-group list-group-flush">
			        <li class="list-group-item">
			        	<p>出演者</p>
			        	<% @film.performer_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
		        	<li class="list-group-item">
		        		<p>制作</p>
			        	<% @film.staff_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
		        	<li class="list-group-item">
		        		<p>ジャンル</p>
			        	<% @film.genre_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
	        	</ul>
			</div>
		</div>
	</div>
	<div class="col">
	</div>
</div>

<!-- 平均スコアの算出 -->
<% starsum = 0 %>
<% @film.reviews.each do |review| %>
	<% review.star.to_i %>
	<% starsum += review.star.to_f %>
<% end %>
<% star_av = starsum.to_f / @film.reviews.count %>

<!-- スコアが無い場合の処理 -->
<% if star_av.to_f.nan? %>
	<% star_av = 0 %>
<% end %>

<!-- レビュー -->
<br>
<div class="row">
	<div class="col">
	</div>
	<div class="col-10">
		<div class="card">
			<div class="card-header">
				<div class="row">
					<div class="col">
						<h4><%= @film.reviews.count %>件のユーザーレビュー</h4>
						<h5>平均スコア：<%= star_av.round(2).to_f %>  <i id="star_av_image"></i></h5>
					</div>
				</div>
			</div>
			<% @reviews.each do |review| %>
				<div class="card-body">
					<p class="card-text">
						<%= attachment_image_tag review.user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '40x40' %>
						<%= link_to review.user.name, user_path(review.user_id) %>
					</p>
					<h5 class="card-title"><%= review.title %></h5>
					<div id="star-rate-<%= review.id %>">評価：<%= review.star.to_f %></div>
						<script>
						  $('#star-rate-<%= review.id %>').raty({
						    size: 36,
						    starOff:  '<%= asset_path('/images/star-off.png') %>',
						    starOn : '<%= asset_path('/images/star-on.png') %>',
						    starHalf: '<%= asset_path('/images/star-half.png') %>',
						    half: true,
						    readOnly: true,
						    score: <%= review.star %>,
						  });
						</script>
					<div class="card-body">
							<%= simple_format(review.body.truncate(100)) %>
							<%= link_to "全部読む", film_review_path(review.film,review), class:"btn btn-link"%>
						<p class="card-text"><small class="text-muted"><%= review.created_at.strftime("%Y/%m/%d/%H:%M") %></small></p>
					</div>
					<% if user_signed_in? %>
						<div id="good_review_button_<%= review.id %>">
							<%= render 'good_reviews/good_review', review: review %>
						</div>
					<% else %>
						<%= review.good_reviews.count %>いいね
					<% end %>
					<% if review.user == current_user %>
						<%= link_to '編集', edit_film_review_path(review.film_id,review), class: "btn btn-light border border-seconday"%>
						<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
	  						削除
						</button>
						<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        レビューを削除しますか？
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-secondary" data-dismiss="modal">
						        	やめる
						        </button>
						        <%= link_to '削除する', film_review_path(review.film_id,review), method: :delete, class: "btn btn-danger"%>
						      </div>
						    </div>
						  </div>
						</div>
					<% end %>
				</div>
			<% end %>
			<div class="card-body">
				<%= paginate @reviews %>
			</div>
		</div>
	</div>
	<div class="col">
	</div>
</div>


<script>
  $('#star_av_image').raty({
    size: 36,
    starOff:  '<%= asset_path('/images/star-off.png') %>',
    starOn : '<%= asset_path('/images/star-on.png') %>',
    starHalf: '<%= asset_path('/images/star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= star_av %>,
  });
</script>