config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admin do
  	resources :users,       only:[:index, :show, :edit, :update, :destroy]
  	resources :films,		only:[:new, :create, :index, :show, :edit, :update, :destroy]
  	resources :tags,		only:[:create, :index, :show, :update]
  	resources :reviews,		only:[:edit, :update, :destroy]
  	get "search_films" => "films#search",as: 'search_films'
  	get "search_users" => "users#search",as: 'search_users'
  end


  resources :users, 		only:[:show, :edit, :update, :resign, :destroy, :follows, :followers] do
  	resources :relationships,	only:[:create, :destroy]
	get :follows, on: :member
    get :followers, on: :member
    # on: :memberはresources以外のアクションへのルーティングも定義
  end

  resources :films,			only:[:index, :show, :edit, :update, :destroy] do
  	resources :wishes,			only:[:create, :destroy]
  	resources :dones,			only:[:create, :destroy]
  	resources :mybests,			only:[:create, :destroy]
  	resources :reviews,			only:[:new, :create, :show, :edit, :update, :destroy] do
  		resources :good_reviews,	only:[:create, :destroy]
  	end
  end
  get "search_films" => "films#search",as: 'search_films'
  get "search_users" => "users#search",as: 'search_users'

  resources :tags,			only:[:create, :index, :show, :update]
  resources :contacts,		only:[:new, :create, :destroy]


  root "films#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/done.rb
class Done < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/models/film.rb
class Film < ApplicationRecord

	acts_as_taggable_on :performers, :staffs, :genres
	acts_as_taggable

	attachment :image

	has_many :reviews, 	dependent: :destroy
	has_many :wishes, 	dependent: :destroy
	has_many :dones, 	dependent: :destroy
	has_many :mybests, 	dependent: :destroy

	validates :title,   	presence: true
	validates :story,		presence: true
	validates :release,		presence: true
	validates :language,	presence: true
	validates :time,		presence: true

	def self.search(search)
		if search.present?
			Film.where(['title LIKE? OR release LIKE? OR language LIKE?', "%#{search}%","%#{search}%","%#{search}%"])
		else
			Film.all
		end
	end

	def reviewed_by?(user)
	    reviewes.where(user_id: user.id).exists?
	end

	def wished_by?(user)
	    wishes.where(user_id: user.id).exists?
	end

	def doned_by?(user)
	    dones.where(user_id: user.id).exists?
	end

	def mybested_by?(user)
	    mybests.where(user_id: user.id).exists?
	end


end

app/models/film_tag.rb
class FilmTag < ApplicationRecord
end

app/models/good_review.rb
class GoodReview < ApplicationRecord

	belongs_to :user
	belongs_to :review

end

app/models/mybest.rb
class Mybest < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"

end

app/models/review.rb
class Review < ApplicationRecord

	has_many :good_reviews,	dependent: :destroy

	belongs_to :user
	belongs_to :film

	validates :user_id, :uniqueness => {:scope => :film_id}

	default_scope -> { order(created_at: :desc)}

	def good_reviewed_by?(user)
    	good_reviews.where(user_id: user.id).exists?
    end

    def self.top_review
    	Review.find(GoodReview.group(:review_id).order('count(review_id) desc').limit(1).pluck(:review_id))
    end

end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }

	has_many :wishes, 		dependent: :destroy
	has_many :dones, 		  	dependent: :destroy
	has_many :mybests, 		dependent: :destroy
	has_many :reviews, 		dependent: :destroy
	has_many :good_reviews, 	dependent: :destroy

	validates :name,          presence: true,
								uniqueness: true,
								length: { minimum: 1, maximum: 20 },
								format: { with: /\A[a-z0-9]+\z/i }
	validates :email, 		presence: true,
								uniqueness: true,
								format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

##refile
	attachment :image

##フォロー機能
	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower

	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following


	def followed_by?(user)
	passive_relationships.find_by(following_id: user.id).present?
	end

##devise

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable

	def email_required?
	false
	end
	def email_changed?
	false
	end

##検索

	def self.search(search)
		if search.present?
			User.where(['name LIKE? OR email LIKE?', "%#{search}%","%#{search}%"])
		else
			User.all
		end
	end

end

app/models/wish.rb
class Wish < ApplicationRecord

	belongs_to :user
	belongs_to :film

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authenticate_admin!, only: [:edit, :update, :destroy]

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
  	@review = Review.new
  	@film = Film.find(params[:film_id])
  end

  def create
  	@film = Film.find(params[:film_id])
  	@review = current_user.reviews.new(review_params)
  	@review.film_id = @film.id
  	if @review.save
  		flash[:success] = 'レビューを投稿しました！'
  		redirect_to film_path(@review.film_id)
  	else
  		flash[:warning] = "投稿に失敗しました！"
        redirect_to film_path(@review.film_id)
    end
  end

  def show
  	@review = Review.find(params[:id])
  end

  def edit
  	@review = Review.find(params[:id])
  end

  def update
  	@review = Review.find(params[:id])
  	if @review.update(review_params)
       flash[:success] = '"' + @review.film.title + '"のレビューを編集しました'
       redirect_to film_path(@review.film_id)
    else
       flash[:warning] = "編集に失敗しました"
       redirect_to film_path(@review.film_id)
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
       flash[:success] = '"' + @review.title + '"を削除しました！'
       redirect_to film_path(@review.film_id)
    else
       flash[:warning] = "削除に失敗しました！"
       redirect_to film_path(@review.film_id)
    end
  end

  private
    def review_params
        params.require(:review).permit(:title, :star, :body)
    end

  	def correct_user
	    @review = Review.find(params[:id])
	    redirect_to film_path(@review.film_id) unless @review.user == current_user
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dones_helper.rb
module DonesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/mybests_helper.rb
module MybestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/reviews/edit.html.erb
<div class="row">
	<div class="col">
	</div>
	<div class="col-3">
	  <div class="card">
	      	<p class="card-body text-center"><%= attachment_image_tag @review.film, :image, fallback: "/images/no_images.png", size: '200x300' %></p>
	        <h5 class="card-text text-center"><%= @review.film.title %></h5>
	        <p class="card-text">
	        	<% @review.film.performer_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	        <p class="card-text">
	        	<% @review.film.staff_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	        <p class="card-text">
	        	<% @review.film.genre_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	  </div>
	</div>
	<div class="col-7">
		<div class="card">
			<h3 class="card-header">レビューを編集する
			</h3>
			<%= form_with model: @review, local: true, url: film_review_path do |f| %>
				<div class="card-body">
					<%= f.label :star, "スコア"%>
					<div class="field" id="star">
						<%= f.hidden_field :star, id: :review_star %>
					</div>
				</div>
				<div class="card-body">
					<%= f.label :title, "タイトル", class: 'card-title' %>
					<%= f.text_field :title , class: 'form-control rounded' %>
				</div>
				<div class="card-body">
					<%= f.label :body, "本文", class: 'card-title' %>
					<%= f.text_area :body, class: 'form-control rounded', size: "60x10" %>
				</div>
				<div class="card-text text-center">
					<%= link_to "戻る", film_path(@review.film), class: "btn btn-light border border-seconday"%>
					<%= f.submit "編集", class: 'btn btn-primary'%>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col">
	</div>
</div>

<script>
$('#star').raty({
  size     : 300,
  starOff:  '<%= asset_path('/images/star-off.png') %>',
  starOn : '<%= asset_path('/images/star-on.png') %>',
  starHalf: '<%= asset_path('/images/star-half.png') %>',
  scoreName: 'review[star]',
  half: true,
});
</script>

app/views/reviews/new.html.erb
<div class="row">
	<div class="col">
	</div>
	<div class="col-3">
	  <div class="card">
	      	<p class="card-body text-center"><%= attachment_image_tag @film, :image, fallback: "/images/no_images.png", size: '200x300' %></p>
	        <h5 class="card-text text-center"><%= @film.title %></h5>
	        <p class="card-text">
	        	<% @film.performer_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	        <p class="card-text">
	        	<% @film.staff_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	        <p class="card-text">
	        	<% @film.genre_list.each do |tag| %>
					<span class="badge badge-info"><%= tag %></span>
				<% end %>
	        </p>
	  </div>
	</div>
	<div class="col-7">
		<div class="card">
			<h3 class="card-header">レビューを投稿する
			</h3>
			<%= form_with model: @review, local: true, url: film_reviews_path do |f| %>
				<div class="card-body">
					<%= f.label :star, "スコア"%>
					<div class="field" id="star">
						<%= f.hidden_field :star, id: :review_star %>
					</div>
				</div>
				<div class="card-body">
					<%= f.label :title, "タイトル", class: 'card-title' %>
					<%= f.text_field :title , class: 'form-control rounded' %>
				</div>
				<div class="card-body">
					<%= f.label :body, "本文", class: 'card-title' %>
					<%= f.text_area :body, class: 'form-control rounded', size: "60x10" %>
				</div>
				<div class="card-text text-center">
					<%= link_to "戻る", film_path(@film), class: "btn btn-light border border-seconday"%>
					<%= f.submit "投稿", class: 'btn btn-primary'%>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col">
	</div>
</div>

<script>
$('#star').raty({
  size     : 300,
  starOff:  '<%= asset_path('/images/star-off.png') %>',
  starOn : '<%= asset_path('/images/star-on.png') %>',
  starHalf: '<%= asset_path('/images/star-half.png') %>',
  scoreName: 'review[star]',
  half: true,
});
</script>

app/views/reviews/show.html.erb
<div class="row">
	<div class="col">
	</div>
	<div class="col-3">
		<div class="card">
	      	<p class="card-body text-center">
	      		<%= link_to film_path(@review.film) do %>
	      			<%= attachment_image_tag @review.film, :image, fallback:"/images/no_images.png", size:"200x300" %>
	      		<% end %>
	      	</p>
	        <h5 class="card-text text-center"><%= @review.film.title %></h5>
			<div class="card-body">
				<ul class="list-group list-group-flush">
			        <li class="list-group-item">
			        	<p>出演者</p>
			        	<% @review.film.performer_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
		        	<li class="list-group-item">
		        		<p>制作</p>
			        	<% @review.film.staff_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
		        	<li class="list-group-item">
		        		<p>ジャンル</p>
			        	<% @review.film.genre_list.each do |tag| %>
							<span class="badge badge-info">
								<%= link_to tag, films_path(tag_name: tag), class:"text-white"%>
							</span>
						<% end %>
		        	</li>
	        	</ul>
			</div>
		</div>
	</div>
	<div class="col-7">
		<div class="card">
			<div class="card-body">
				<p class="card-text">
					<%= attachment_image_tag @review.user, :image, class:"profile-image", fallback: "/images/no_image_profile.jpg", size: '40x40' %>
					<%= link_to @review.user.name, user_path(@review.user_id) %>
				</p>
				<h5 class="card-title"><%= @review.title %></h5>
				<div id="star-rate-<%= @review.id %>">評価：<%= @review.star %></div>
					<script>
					  $('#star-rate-<%= @review.id %>').raty({
					    size: 36,
					    starOff:  '<%= asset_path('/images/star-off.png') %>',
					    starOn : '<%= asset_path('/images/star-on.png') %>',
					    starHalf: '<%= asset_path('/images/star-half.png') %>',
					    half: true,
					    readOnly: true,
					    score: <%= @review.star %>,
					  });
					</script>
				<div class="card-body">
					<p class="card-text"><%= simple_format(@review.body) %></p>
				</div>
				<% if user_signed_in? %>
					<div id="good_review_button_<%= @review.id %>">
						<%= render 'good_reviews/good_review', review: @review %>
					</div>
				<% else %>
					<%= @review.good_reviews.count %>いいね
				<% end %>
				<% if @review.user == current_user %>
					<%= link_to '編集', edit_film_review_path(@review.film_id,@review), class: "btn btn-light border border-seconday"%>
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
							削除
					</button>
					<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        レビューを削除しますか？
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-secondary" data-dismiss="modal">
					        	やめる
					        </button>
					        <%= link_to '削除する', film_review_path(@review), method: :delete, class: "btn btn-danger"%>
					      </div>
					    </div>
					  </div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col">
	</div>
</div>